# Generated by Django 6.0.2 on 2026-02-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("office_phone", models.CharField(blank=True, max_length=20)),
                ("cell_phone", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_leader", models.CharField(max_length=100)),
                ("atl", models.CharField(max_length=100)),
                (
                    "employer",
                    models.CharField(
                        choices=[
                            ("WSP USA", "WSP USA"),
                            ("South Col", "South Col"),
                            ("Lu Eng", "Lu Eng"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
    ]
